apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sf-github-metrics
  namespace: teamcrm
spec:
  ingresses:
    - https://sf-github-metrics.ekstern.dev.nav.no
  image: '{{image}}'
  port: 8080
  replicas:
    max: 1
    min: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  observability:
    logging:
      destinations:
        - id: loki
  env:
    - name: PROMGATEADDRESS
      value: http://prometheus-pushgateway.nais-system:9091
  accessPolicy:
    outbound:
      rules:
        - application: prometheus-pushgateway
          namespace: nais-system
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: pgdb
