apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sf-github-metrics
  namespace: teamcrm
spec:
  ingresses:
    - https://sf-github-metrics.intern.dev.nav.no
  image: "{{image}}"
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  observability:
    logging:
      destinations:
        - id: loki
